# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Android CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
        matrix:
          api-level: [30, 33]
          target: [google_apis]
          java-version: [11]
          architecture: [x86_64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run unit tests
        run: ./gradlew build

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-${{ matrix.api-level }}-${{ matrix.target}}-${{ matrix.java-version }}-${{ matrix.architecture }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: ${{ matrix.target }}
          arch: ${{ matrix.architecture }}
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          target: ${{ matrix.target }}
          arch: ${{ matrix.architecture }}
          script: ./gradlew connectedAndroidTest

